# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20190312_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
