# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20190312_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 12, 45, 26, 541445)),
        ),
        migrations.AddField(
            model_name='piece',
            name='imgfile',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
