# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20190320_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 12, 45, 39, 134563)),
        ),
    ]
