# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-20 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20190320_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 14, 23, 28, 990083)),
        ),
    ]
