# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20190320_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='rating',
        ),
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 11, 3, 0, 127204)),
        ),
    ]
