# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0022_auto_20190321_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 11, 54, 37, 479221)),
        ),
        migrations.AlterField(
            model_name='piece',
            name='imgfile',
            field=models.ImageField(default='', upload_to='sheets'),
        ),
    ]
