# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0029_auto_20190321_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 13, 7, 1, 779542)),
        ),
    ]
