# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-21 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0036_auto_20190321_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 14, 24, 18, 549751)),
        ),
    ]
