# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0037_auto_20190321_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 14, 38, 12, 556304)),
        ),
    ]
