# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0040_auto_20190322_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 35, 28, 214210)),
        ),
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
